language: php

php:
  - 7.2

before_script:
  - composer install
  - cp .env.dist .env

script:
  - ./bin/phpunit

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always